language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    recipients:
      - rjsckdd12@gmail.com

before_install:
  - chmod +x mvnw
