language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw clean package"

notifications:
  email:
    recipients:
      - rjsckdd12@gmail.com
